### ISSUE TITLE
undefined reference to 'readline' and 'add_history'

### ISSUE THREAD

**Issue by trevortomesh** [indradhanush/rc-shell#1] opened 2018-04-27 02:28 UTC
gcc -g -Wall -Wpedantic -lreadline common.c signal_handling.c builtin.c input.c job_control.c helpers.c shell.c main.c  -o rcshell && chmod +x rcshell
/tmp/ccLmGcpv.o: In function `main':
/home/trevor/Documents/GitHub/rc-shell/src/main.c:53: undefined reference to `readline'
/home/trevor/Documents/GitHub/rc-shell/src/main.c:59: undefined reference to `add_history'
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by indradhanush** [comment] 2018-05-31 08:52
@trevortomesh Thanks for the issue. However I was unable to reproduce this on my machine. I am able to build the project by running `make build` from the `src/` directory or by directly running:

```
gcc -g -Wall -Wpedantic -lreadline common.c signal_handling.c builtin.c input.c job_control.c helpers.c shell.c main.c  -o rcshell && chmod +x rcshell
```

Could you please tell me more about the system you're trying to run this on?

**Comment by indradhanush** [comment] 2018-05-31 08:54
Additionally you need to ensure that you have the `libreadline-dev` package installed in your system.

**Comment by indradhanush** [comment] 2018-06-04 02:52
@trevortomesh I am closing this issue. Please feel free to reopen if the error still persists.

**Closed as completed by indradhanush** 2018-06-04 02:52 UTC

**Comment by NRizzoInc** [comment] 2021-04-10 23:26
I know this is old, but I had the same issue and fixed it with [this](https://askubuntu.com/a/523944). TLDR: put `-lreadline` at the end

**Comment by sammiearchie77** [comment] 2022-11-01 21:48
This is also old but the `-lreadline` at the end of the compiler flag is still helpful

**Comment by kendfss** [comment] 2022-12-20 18:33
Even older now, but anybody got any other suggestions?
That said, I'm trying to build [something else](https://www.buildyourownlisp.com/chapter4_interactive_prompt), but I've tried building it with libedit as well. Both are installed (according to apt, dpkg-query and pkg-config) but seem to be unable to surmount this issue at link-time.
